# bash completion for vpnman - generated by tools/gen_completions.py, do not edit
_vpnman() {
    local cur cmd opts choices names
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    cmd="${COMP_WORDS[1]}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "about add autostart backup block blocks bypass cleanup connect connections daemon disconnect dns doctor down edit failover fav get group gui history import leaktest list lock logs ls menu netproxy networks ping protocols proxy remove rm routes schedule service set shell split status unblock unfav up update --version --help" -- "$cur") )
        return
    fi
    case "$cmd" in
        about)
            opts=""
            choices=""
            names=0 ;;
        add)
            opts="--protocol --server --port --user --ask-password --option -o"
            choices=""
            names=0 ;;
        autostart)
            opts="--login-app"
            choices=""
            names=0 ;;
        backup)
            opts="--replace --settings --force"
            choices="export import"
            names=0 ;;
        block)
            opts=""
            choices=""
            names=1 ;;
        blocks)
            opts="--proto --note --for --until-reboot --json"
            choices="list status add remove rm enable disable on off"
            names=0 ;;
        bypass)
            opts=""
            choices="list add remove rm available on off mode"
            names=0 ;;
        cleanup)
            opts="--force"
            choices=""
            names=0 ;;
        connect)
            opts="--fastest --last --no-wait --timeout"
            choices=""
            names=1 ;;
        connections)
            opts="--listening -l --local --resolve -r --watch -w --csv --json"
            choices=""
            names=0 ;;
        daemon)
            opts=""
            choices=""
            names=0 ;;
        disconnect)
            opts=""
            choices=""
            names=0 ;;
        dns)
            opts=""
            choices=""
            names=0 ;;
        doctor)
            opts="--fix"
            choices=""
            names=0 ;;
        down)
            opts=""
            choices=""
            names=0 ;;
        edit)
            opts=""
            choices=""
            names=1 ;;
        failover)
            opts="--clear"
            choices=""
            names=1 ;;
        fav)
            opts=""
            choices=""
            names=1 ;;
        get)
            opts=""
            choices=""
            names=0 ;;
        group)
            opts="--ask-password"
            choices="list edit"
            names=0 ;;
        gui)
            opts="--background"
            choices=""
            names=0 ;;
        history)
            opts="-n --lines --json --clear"
            choices=""
            names=0 ;;
        import)
            opts="--name --protocol --user --password --ask-password --stunnel --stunnel-sni --stunnel-ca --stunnel-verify"
            choices=""
            names=0 ;;
        leaktest)
            opts="--json"
            choices=""
            names=0 ;;
        list)
            opts="--latency -l --names --sort --json"
            choices=""
            names=0 ;;
        lock)
            opts=""
            choices="on off status"
            names=0 ;;
        logs)
            opts="-f --follow -n --lines"
            choices=""
            names=0 ;;
        ls)
            opts="--latency -l --names --sort --json"
            choices=""
            names=0 ;;
        menu)
            opts=""
            choices=""
            names=0 ;;
        netproxy)
            opts="--user --ask-password --json"
            choices="status on off set clear ignore apps dns udp"
            names=0 ;;
        networks)
            opts=""
            choices="show trust untrust"
            names=0 ;;
        ping)
            opts=""
            choices=""
            names=1 ;;
        protocols)
            opts="--json"
            choices=""
            names=0 ;;
        proxy)
            opts="--name --group --all --fastest --qr --latency -l --json"
            choices="list show link add remove rm edit use on off order mode set status ping refresh sources failover"
            names=0 ;;
        remove)
            opts=""
            choices=""
            names=1 ;;
        rm)
            opts=""
            choices=""
            names=1 ;;
        routes)
            opts=""
            choices="list add remove rm"
            names=0 ;;
        schedule)
            opts="--name --days --start --end --profile"
            choices="list add remove rm enable disable on off"
            names=0 ;;
        service)
            opts="--init"
            choices="install uninstall enable disable start stop restart status"
            names=0 ;;
        set)
            opts=""
            choices=""
            names=0 ;;
        shell)
            opts=""
            choices=""
            names=0 ;;
        split)
            opts=""
            choices="list add remove rm available on off mode"
            names=0 ;;
        status)
            opts="--json"
            choices=""
            names=0 ;;
        unblock)
            opts=""
            choices=""
            names=1 ;;
        unfav)
            opts=""
            choices=""
            names=1 ;;
        up)
            opts="--fastest --last --no-wait --timeout"
            choices=""
            names=1 ;;
        update)
            opts="--json"
            choices=""
            names=0 ;;
        *) return ;;
    esac
    case "${COMP_WORDS[COMP_CWORD-1]}" in
        --protocol) COMPREPLY=( $(compgen -W "openvpn wireguard amneziawg openconnect openfortivpn ikev2 sstp pptp vpnc tailscale netbird zerotier nebula networkmanager custom" -- "$cur") ); return ;;
        --login-app) COMPREPLY=( $(compgen -W "on off" -- "$cur") ); return ;;
        --proto) COMPREPLY=( $(compgen -W "any tcp udp" -- "$cur") ); return ;;
        --stunnel-verify) COMPREPLY=( $(compgen -W "none system ca" -- "$cur") ); return ;;
        --sort) COMPREPLY=( $(compgen -W "name latency group" -- "$cur") ); return ;;
        --init) COMPREPLY=( $(compgen -W "systemd runit openrc sysv openbsd-rc bsd-rc" -- "$cur") ); return ;;
    esac
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return
    fi
    COMPREPLY=( $(compgen -W "$choices" -- "$cur") )
    if [ "$names" = 1 ]; then
        local IFS=$'\n' n
        for n in $(vpnman list --names 2>/dev/null); do
            [[ "${n,,}" == "${cur,,}"* ]] && COMPREPLY+=( "${n// /\\ }" )
        done
    fi
}
complete -F _vpnman vpnman
