#!/bin/sh
# VPNMan installer - POSIX sh, runs on Linux (systemd, runit, OpenRC, SysV) and the BSDs.
#
#   sudo ./install.sh                  install to /usr/local, set up the service for this machine
#   sudo ./install.sh --prefix /usr    choose another prefix
#   DESTDIR=/tmp/stage ./install.sh --init systemd --no-post    stage files for a package
#   sudo ./install.sh --uninstall [--purge]
#   sudo ./install.sh --install-deps   install dependencies with the native package manager first
set -eu

PREFIX=/usr/local
INIT=auto
DO_POST=1
UNINSTALL=0
PURGE=0
DEPS=0
GROUP=vpnman
SRC=$(cd "$(dirname "$0")" && pwd)
DESTDIR=${DESTDIR:-}

usage() {
    sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'
    cat <<USAGE

Options:
  --prefix DIR        installation prefix (default: /usr/local)
  --init SYSTEM       auto | systemd | sysv | openrc | runit | openbsd | freebsd | all-linux | none
  --no-post           do not create the group, touch caches or enable the service
  --uninstall         remove VPNMan (add --purge to also delete /etc/vpnman profiles/settings)
  --install-deps      install runtime dependencies first (apt, dnf, pacman, xbps, apk, zypper, pkg_add, pkg)
  -h, --help          show this help
USAGE
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix) PREFIX=$2; shift ;;
        --prefix=*) PREFIX=${1#*=} ;;
        --init) INIT=$2; shift ;;
        --init=*) INIT=${1#*=} ;;
        --no-post|--no-service) DO_POST=0 ;;
        --uninstall) UNINSTALL=1 ;;
        --purge) PURGE=1 ;;
        --install-deps) DEPS=1 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

say() { printf '==> %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

OS=$(uname -s)
if [ -z "$DESTDIR" ] && [ "$(id -u)" -ne 0 ]; then
    die "run as root (try: sudo $0 $*)"
fi

LIBDIR=$PREFIX/lib/vpnman
SHAREDIR=$PREFIX/share
BINDIR=$PREFIX/bin
MANDIR=$SHAREDIR/man/man1
[ "$OS" = OpenBSD ] && MANDIR=$PREFIX/man/man1
D=$DESTDIR

detect_init() {
    case "$OS" in
        OpenBSD) echo openbsd; return ;;
        FreeBSD|NetBSD|DragonFly) echo freebsd; return ;;
        Darwin) echo none; return ;;
    esac
    if [ -d /run/systemd/system ]; then echo systemd
    elif [ "$(cat /proc/1/comm 2>/dev/null)" = runit ] || [ -d /run/runit ]; then echo runit
    elif [ -d /run/openrc ] || [ -x /sbin/openrc-run ]; then echo openrc
    elif [ -d /etc/init.d ]; then echo sysv
    elif have sv && { [ -d /etc/sv ] || [ -d /var/service ]; }; then echo runit
    else echo none
    fi
}

install_deps() {
    say "Installing dependencies"
    if have apt-get; then
        apt-get update && apt-get install -y python3 python3-gi gir1.2-gtk-4.0 gir1.2-adw-1 openvpn wireguard-tools nftables iproute2 openresolv
    elif have dnf; then
        dnf install -y python3 python3-gobject gtk4 libadwaita openvpn wireguard-tools nftables iproute
    elif have pacman; then
        pacman -S --needed --noconfirm python python-gobject gtk4 libadwaita openvpn wireguard-tools nftables iproute2
    elif have xbps-install; then
        xbps-install -Sy python3 python3-gobject gtk4 libadwaita openvpn wireguard-tools nftables iproute2
    elif have apk; then
        apk add python3 py3-gobject3 gtk4.0 libadwaita openvpn wireguard-tools nftables iproute2
    elif have zypper; then
        zypper install -y python3 python3-gobject typelib-1_0-Gtk-4_0 typelib-1_0-Adw-1 openvpn wireguard-tools nftables iproute2
    elif have pkg_add; then
        pkg_add python3 py3-gobject3 gtk4 libadwaita openvpn wireguard-tools
    elif have pkg; then
        pkg install -y python3 py311-gobject3 gtk4 libadwaita openvpn wireguard-tools
    else
        die "no supported package manager found; install python3, PyGObject, GTK4, libadwaita, openvpn, wireguard-tools, nftables/iptables/pf manually"
    fi
    cat <<NOTE
Optional protocol tools: openconnect (AnyConnect/GlobalProtect/Pulse), openfortivpn, sstp-client, pptp-linux,
strongswan (swanctl), vpnc, tailscale, netbird, zerotier-one, nebula, NetworkManager (nmcli).
NOTE
}

wrapper() {  # wrapper <path> <python args...>
    out=$1; shift
    mkdir -p "$(dirname "$out")"
    cat > "$out" <<WRAP
#!/bin/sh
# generated by VPNMan install.sh
PY=\${VPNMAN_PYTHON:-}
if [ -z "\$PY" ]; then
    for c in python3 python3.13 python3.12 python3.11 python3.10 python3.9 python; do
        if command -v "\$c" >/dev/null 2>&1; then PY=\$c; break; fi
    done
fi
export PYTHONPATH="$LIBDIR\${PYTHONPATH:+:\$PYTHONPATH}"
export VPNMAN_DATA_DIR="$SHAREDIR/vpnman"
exec "\$PY" -m vpnman $* "\$@"
WRAP
    chmod 755 "$out"
}

render() {  # render <template> <dest> <mode>
    mkdir -p "$(dirname "$D$2")"
    sed "s|@BINDIR@|$BINDIR|g" "$1" > "$D$2"
    chmod "$3" "$D$2"
}

systemd_unit_dir() {
    if [ -n "$DESTDIR" ] || [ "$PREFIX" = /usr ]; then echo /usr/lib/systemd/system
    else echo /etc/systemd/system; fi
}

install_init() {
    case "$1" in
        systemd) render "$SRC/data/init/vpnmand.service" "$(systemd_unit_dir)/vpnmand.service" 644 ;;
        sysv) render "$SRC/data/init/vpnmand.sysv" /etc/init.d/vpnmand 755 ;;
        openrc) render "$SRC/data/init/vpnmand.openrc" /etc/init.d/vpnmand 755 ;;
        runit)
            sv=/etc/sv; [ -d /etc/runit/sv ] && [ ! -d /etc/sv ] && sv=/etc/runit/sv
            render "$SRC/data/init/runit/run" "$sv/vpnmand/run" 755
            render "$SRC/data/init/runit/log/run" "$sv/vpnmand/log/run" 755 ;;
        openbsd) render "$SRC/data/init/vpnmand.openbsd" /etc/rc.d/vpnmand 555 ;;
        freebsd) render "$SRC/data/init/vpnmand.freebsd" /usr/local/etc/rc.d/vpnmand 555 ;;
        none) ;;
        *) die "unknown init system: $1" ;;
    esac
}

refresh_icon_cache() {
    for t in gtk4-update-icon-cache gtk-update-icon-cache; do
        if have "$t"; then "$t" -q -f -t "$SHAREDIR/icons/hicolor" 2>/dev/null && break; fi
    done
    if have update-desktop-database; then update-desktop-database -q "$SHAREDIR/applications" 2>/dev/null; fi
    return 0
}

uninstall() {
    say "Removing VPNMan"
    INIT_NOW=$INIT; [ "$INIT_NOW" = auto ] && INIT_NOW=$(detect_init)
    case "$INIT_NOW" in
        systemd) systemctl disable --now vpnmand 2>/dev/null || true ;;
        runit) rm -f /var/service/vpnmand /etc/service/vpnmand 2>/dev/null || true ;;
        openrc) rc-service vpnmand stop 2>/dev/null || true; rc-update del vpnmand default 2>/dev/null || true ;;
        sysv) /etc/init.d/vpnmand stop 2>/dev/null || true; update-rc.d -f vpnmand remove 2>/dev/null || true ;;
        openbsd) rcctl disable vpnmand 2>/dev/null || true; rcctl stop vpnmand 2>/dev/null || true ;;
    esac
    rm -rf "$D$LIBDIR" "$D$SHAREDIR/vpnman"
    rm -f "$D$BINDIR/vpnman" "$D$BINDIR/vpnmand" "$D$BINDIR/vpnman-gtk"
    rm -f "$D$SHAREDIR/applications/io.github.smiley_mcsmiles.VPNMan.desktop" \
          "$D$SHAREDIR/metainfo/io.github.smiley_mcsmiles.VPNMan.metainfo.xml" \
          "$D$SHAREDIR/icons/hicolor/scalable/apps/io.github.smiley_mcsmiles.VPNMan.svg" \
          "$D$MANDIR/vpnman.1"
    rm -f "$D$SHAREDIR"/icons/hicolor/symbolic/apps/io.github.smiley_mcsmiles.VPNMan*.svg
    if [ -z "$DESTDIR" ]; then refresh_icon_cache; fi
    rm -f "$D/etc/systemd/system/vpnmand.service" "$D/usr/lib/systemd/system/vpnmand.service" \
          "$D/etc/init.d/vpnmand" "$D/etc/rc.d/vpnmand" "$D/usr/local/etc/rc.d/vpnmand"
    rm -rf "$D/etc/sv/vpnmand" "$D/etc/runit/sv/vpnmand"
    if [ "$PURGE" -eq 1 ]; then
        rm -rf "$D/etc/vpnman"
        say "Purged /etc/vpnman"
    else
        say "Kept /etc/vpnman (profiles, settings). Use --purge to delete."
    fi
    have systemctl && [ -z "$DESTDIR" ] && systemctl daemon-reload 2>/dev/null || true
    # a stale kill switch must never outlive the software that owns it
    if [ -z "$DESTDIR" ]; then
        have nft && nft delete table inet vpnman 2>/dev/null || true
    fi
    exit 0
}

[ "$UNINSTALL" -eq 1 ] && uninstall
[ "$DEPS" -eq 1 ] && install_deps

have python3 || have python || die "python3 is required"
[ -d "$SRC/vpnman" ] || die "run install.sh from the VPNMan source directory"

say "Installing VPNMan to $D$PREFIX"
rm -rf "$D$LIBDIR"
mkdir -p "$D$LIBDIR"
cp -R "$SRC/vpnman" "$D$LIBDIR/vpnman"
find "$D$LIBDIR" -name __pycache__ -type d -prune -exec rm -rf {} + 2>/dev/null || true

mkdir -p "$D/etc/vpnman" && chmod 700 "$D/etc/vpnman"
mkdir -p "$D$SHAREDIR/vpnman"
cp -R "$SRC/data/init" "$D$SHAREDIR/vpnman/init"

wrapper "$D$BINDIR/vpnman"
wrapper "$D$BINDIR/vpnmand" daemon
wrapper "$D$BINDIR/vpnman-gtk" gui

mkdir -p "$D$SHAREDIR/applications" "$D$SHAREDIR/metainfo" "$D$MANDIR" \
         "$D$SHAREDIR/icons/hicolor/scalable/apps" "$D$SHAREDIR/icons/hicolor/symbolic/apps"
cp "$SRC/data/io.github.smiley_mcsmiles.VPNMan.desktop" "$D$SHAREDIR/applications/"
cp "$SRC/data/io.github.smiley_mcsmiles.VPNMan.metainfo.xml" "$D$SHAREDIR/metainfo/"
cp "$SRC/data/icons/hicolor/scalable/apps/"*.svg "$D$SHAREDIR/icons/hicolor/scalable/apps/"
cp "$SRC/data/icons/hicolor/symbolic/apps/"*.svg "$D$SHAREDIR/icons/hicolor/symbolic/apps/"
# A private, cache-free copy: GTK trusts a stale icon-theme.cache (it only checks the mtime of hicolor/ itself),
# so the app falls back to this copy - and hands it to the tray host - when the system theme misses the icons.
mkdir -p "$D$SHAREDIR/vpnman/icons"
cp -R "$SRC/data/icons/hicolor" "$D$SHAREDIR/vpnman/icons/"
cp "$SRC/data/vpnman.1" "$D$MANDIR/vpnman.1"
# the launcher must find the wrapper on PATH even for non-default prefixes
sed -i.bak "s|^Exec=.*|Exec=$BINDIR/vpnman-gtk|" "$D$SHAREDIR/applications/io.github.smiley_mcsmiles.VPNMan.desktop" 2>/dev/null \
    && rm -f "$D$SHAREDIR/applications/io.github.smiley_mcsmiles.VPNMan.desktop.bak"

[ "$INIT" = auto ] && INIT=$(detect_init)
case "$INIT" in
    all-linux) install_init systemd; install_init sysv ;;
    *) install_init "$INIT" ;;
esac
say "Service definition installed for: $INIT"

if [ "$DO_POST" -eq 1 ] && [ -z "$DESTDIR" ]; then
    mkdir -p /etc/vpnman && chmod 700 /etc/vpnman
    if ! (getent group "$GROUP" >/dev/null 2>&1 || grep -q "^$GROUP:" /etc/group); then
        say "Creating group '$GROUP'"
        if have groupadd; then groupadd -r "$GROUP" 2>/dev/null || groupadd "$GROUP"
        elif have addgroup; then addgroup -S "$GROUP"
        elif have pw; then pw groupadd "$GROUP"
        fi
    fi
    TARGET_USER=${SUDO_USER:-${DOAS_USER:-}}
    if [ -n "$TARGET_USER" ] && [ "$TARGET_USER" != root ]; then
        say "Adding $TARGET_USER to group '$GROUP'"
        if have usermod && [ "$OS" = Linux ]; then usermod -aG "$GROUP" "$TARGET_USER"
        elif have adduser && [ "$OS" = Linux ]; then adduser "$TARGET_USER" "$GROUP"
        elif [ "$OS" = OpenBSD ]; then
            others=$(id -Gn "$TARGET_USER" | tr ' ' ',')
            usermod -G "$others,$GROUP" "$TARGET_USER"
        elif have pw; then pw groupmod "$GROUP" -m "$TARGET_USER"
        fi
    fi
    refresh_icon_cache
    case "$INIT" in
        systemd) systemctl daemon-reload; systemctl enable --now vpnmand ;;
        runit)
            link=/var/service; [ -d /var/service ] || { [ -d /etc/service ] && link=/etc/service; }
            sv=/etc/sv; [ -d /etc/runit/sv ] && [ ! -d /etc/sv ] && sv=/etc/runit/sv
            ln -sf "$sv/vpnmand" "$link/vpnmand" ;;
        openrc) rc-update add vpnmand default; rc-service vpnmand start ;;
        sysv)
            if have update-rc.d; then update-rc.d vpnmand defaults
            elif have chkconfig; then chkconfig --add vpnmand
            fi
            /etc/init.d/vpnmand start ;;
        openbsd) rcctl enable vpnmand; rcctl start vpnmand ;;
        freebsd) sysrc vpnmand_enable=YES >/dev/null; service vpnmand start ;;
    esac
fi

cat <<DONE

VPNMan is installed.
  GUI:  vpnman-gtk          CLI:  vpnman   (interactive menu)   Daemon: vpnmand
  Import a profile:  vpnman import my.ovpn      Kill switch:  vpnman lock on
Open the app from your menu - no further setup needed. Run "vpnman doctor" to see which protocols have their tools installed.
DONE
