#!/usr/bin/env python3
"""Build an Arch Linux package (.pkg.tar.xz) from a staged directory tree without makepkg or pacman.

usage: mkarch.py <staged-root> <output.pkg.tar.xz> --name N --version V [--pkgrel 1] --desc D --url U
                 [--license MIT] [--depend X ...] [--optdepend 'x: why' ...] [--install script.sh]

A package is a tar archive (any libarchive compression; xz here, because Python always has it) whose first entries
are the dot-files .PKGINFO (metadata) and .INSTALL (scriptlets), followed by the files.  Works on any distribution,
so packages can be built on Fedora, Debian, Void ... and installed with `pacman -U`.
"""
import argparse
import os
import sys
import tarfile
import time


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("out")
    ap.add_argument("--name", required=True)
    ap.add_argument("--version", required=True)
    ap.add_argument("--pkgrel", default="1")
    ap.add_argument("--desc", required=True)
    ap.add_argument("--url", required=True)
    ap.add_argument("--license", default="MIT")
    ap.add_argument("--packager", default="VPNMan contributors")
    ap.add_argument("--depend", action="append", default=[])
    ap.add_argument("--optdepend", action="append", default=[])
    ap.add_argument("--install")
    a = ap.parse_args()
    now = int(os.environ.get("SOURCE_DATE_EPOCH", time.time()))

    entries, size = [], 0
    for dirpath, dirs, files in os.walk(a.root):
        dirs.sort()
        for n in sorted(dirs + files):
            full = os.path.join(dirpath, n)
            entries.append((full, os.path.relpath(full, a.root)))
            if os.path.isfile(full) and not os.path.islink(full):
                size += os.path.getsize(full)

    info = ["# Generated by VPNMan packaging/mkarch.py",
            "pkgname = %s" % a.name, "pkgbase = %s" % a.name, "pkgver = %s-%s" % (a.version, a.pkgrel),
            "pkgdesc = %s" % a.desc, "url = %s" % a.url, "builddate = %d" % now, "packager = %s" % a.packager,
            "size = %d" % size, "arch = any", "license = %s" % a.license]
    info += ["depend = %s" % d for d in a.depend]
    info += ["optdepend = %s" % d for d in a.optdepend]
    meta = ("\n".join(info) + "\n").encode()

    def norm(ti):
        ti.uid = ti.gid = 0
        ti.uname = ti.gname = "root"
        ti.mtime = now
        return ti

    def add_bytes(tf, name, data, mode=0o644):
        import io
        ti = tarfile.TarInfo(name)
        ti.size, ti.mode = len(data), mode
        tf.addfile(norm(ti), io.BytesIO(data))

    with tarfile.open(a.out, "w:xz", format=tarfile.PAX_FORMAT) as tf:
        add_bytes(tf, ".PKGINFO", meta)
        if a.install:
            with open(a.install, "rb") as fh:
                add_bytes(tf, ".INSTALL", fh.read())
        for full, rel in entries:
            tf.add(full, arcname=rel, filter=norm, recursive=False)
    print(a.out)


if __name__ == "__main__":
    sys.exit(main())
