#!/usr/bin/env python3
"""Generate the bash / zsh / fish completions from the real argparse definition, so they cannot drift.

    python3 tools/gen_completions.py          # rewrite data/completions/*
    python3 tools/gen_completions.py --check  # exit 1 if the checked-in files are stale (used by the tests)
"""
import argparse
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, ROOT)

from vpnman import cli  # noqa: E402

# commands whose positional arguments are profile names (completed from `vpnman list --names`)
PROFILE_CMDS = {"connect", "up", "remove", "rm", "edit", "fav", "unfav", "block", "unblock", "ping", "failover"}


def model():
    ap = cli.build_parser()
    sub = next(a for a in ap._actions if isinstance(a, argparse._SubParsersAction))
    helps = {}
    for ca in sub._choices_actions:
        names = ca.metavar or ca.dest
        for n in [x.strip() for x in names.replace("(", ",").replace(")", "").split(",")]:
            helps[n] = ca.help or ""
    cmds = {}
    for name, sp in sub.choices.items():
        opts, choices = [], []
        for a in sp._actions:
            if a.help == argparse.SUPPRESS and not a.option_strings:
                continue
            if a.option_strings:
                if a.dest == "help":
                    continue
                opts.append((a.option_strings, a.help or "", list(a.choices or [])))
            elif a.choices:
                choices += list(a.choices)
        cmds[name] = {"help": helps.get(name, ""), "opts": opts, "choices": choices}
    return cmds


def flat(opts):
    return [o for strs, _h, _c in opts for o in strs]


def q(text):
    return text.replace("'", "'\\''").replace("\n", " ")


def bash(cmds):
    out = ["# bash completion for vpnman - generated by tools/gen_completions.py, do not edit", "_vpnman() {",
           "    local cur cmd opts choices names", "    COMPREPLY=()", '    cur="${COMP_WORDS[COMP_CWORD]}"',
           '    cmd="${COMP_WORDS[1]}"',
           '    if [ "$COMP_CWORD" -eq 1 ]; then',
           '        COMPREPLY=( $(compgen -W "%s --version --help" -- "$cur") )' % " ".join(sorted(cmds)),
           "        return", "    fi", '    case "$cmd" in']
    for name, c in sorted(cmds.items()):
        out.append("        %s)" % name)
        out.append('            opts="%s"' % " ".join(flat(c["opts"])))
        out.append('            choices="%s"' % " ".join(c["choices"]))
        out.append("            names=%d ;;" % (1 if name in PROFILE_CMDS else 0))
    out += ["        *) return ;;", "    esac",
            '    case "${COMP_WORDS[COMP_CWORD-1]}" in']
    for name, c in sorted(cmds.items()):
        for strs, _h, ch in c["opts"]:
            if ch:
                pass
    seen = {}
    for name, c in sorted(cmds.items()):
        for strs, _h, ch in c["opts"]:
            if ch:
                seen.setdefault(tuple(strs), ch)
    for strs, ch in seen.items():
        out.append('        %s) COMPREPLY=( $(compgen -W "%s" -- "$cur") ); return ;;' % ("|".join(strs), " ".join(ch)))
    out += ["    esac",
            '    if [[ "$cur" == -* ]]; then',
            '        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )', "        return", "    fi",
            '    COMPREPLY=( $(compgen -W "$choices" -- "$cur") )',
            '    if [ "$names" = 1 ]; then',
            "        local IFS=$'\\n' n",
            '        for n in $(vpnman list --names 2>/dev/null); do',
            '            [[ "${n,,}" == "${cur,,}"* ]] && COMPREPLY+=( "${n// /\\\\ }" )',
            "        done", "    fi", "}", "complete -F _vpnman vpnman", ""]
    return "\n".join(out)


def zsh(cmds):
    out = ["#compdef vpnman", "# zsh completion for vpnman - generated by tools/gen_completions.py, do not edit", "",
           "_vpnman_profiles() {", "    local -a names", "    names=(\"${(@f)$(vpnman list --names 2>/dev/null)}\")",
           "    _describe 'profile' names", "}", "", "_vpnman() {", "    local -a commands", "    commands=("]
    for name, c in sorted(cmds.items()):
        out.append("        '%s:%s'" % (name, q(c["help"]).replace(":", " -")))
    out += ["    )", "    if (( CURRENT == 2 )); then", "        _describe 'command' commands", "        return",
            "    fi", "    case $words[2] in"]
    for name, c in sorted(cmds.items()):
        args = []
        for strs, h, ch in c["opts"]:
            tail = "[%s]" % q(h).replace("[", "(").replace("]", ")")
            if ch:
                tail += ":value:(%s)" % " ".join(ch)
            if len(strs) == 1:
                args.append("'%s%s'" % (strs[0], tail))
            else:
                args.append("'(%s)'{%s}'%s'" % (" ".join(strs), ",".join(strs), tail))
        if c["choices"]:
            args.append("'1:action:(%s)'" % " ".join(c["choices"]))
        elif name in PROFILE_CMDS:
            args.append("'*:profile:_vpnman_profiles'")
        out.append("        %s) _arguments %s ;;" % (name, " ".join(args) if args else "'*:: :'"))
    out += ["    esac", "}", "", '_vpnman "$@"', ""]
    return "\n".join(out)


def fish(cmds):
    out = ["# fish completion for vpnman - generated by tools/gen_completions.py, do not edit",
           "complete -c vpnman -f"]
    names = " ".join(sorted(cmds))
    for name, c in sorted(cmds.items()):
        out.append("complete -c vpnman -n '__fish_use_subcommand' -a %s -d '%s'" % (name, q(c["help"])))
    for name, c in sorted(cmds.items()):
        cond = "__fish_seen_subcommand_from %s" % name
        for strs, h, ch in c["opts"]:
            flags = []
            for s in strs:
                flags.append("-l %s" % s[2:] if s.startswith("--") else "-s %s" % s[1:])
            extra = " -x -a '%s'" % " ".join(ch) if ch else ""
            out.append("complete -c vpnman -n '%s' %s -d '%s'%s" % (cond, " ".join(flags), q(h), extra))
        if c["choices"]:
            out.append("complete -c vpnman -n '%s' -a '%s'" % (cond, " ".join(c["choices"])))
        if name in PROFILE_CMDS:
            out.append("complete -c vpnman -n '%s' -a '(vpnman list --names 2>/dev/null)'" % cond)
    out.append("")
    return "\n".join(out)


FILES = {"vpnman.bash": bash, "_vpnman": zsh, "vpnman.fish": fish}


def render():
    cmds = model()
    return {name: fn(cmds) for name, fn in FILES.items()}


if __name__ == "__main__":
    out_dir = os.path.join(ROOT, "data", "completions")
    texts = render()
    if "--check" in sys.argv:
        stale = [n for n, t in texts.items() if not os.path.exists(os.path.join(out_dir, n))
                 or open(os.path.join(out_dir, n)).read() != t]
        if stale:
            print("stale completions: %s (run tools/gen_completions.py)" % ", ".join(stale), file=sys.stderr)
            sys.exit(1)
        sys.exit(0)
    os.makedirs(out_dir, exist_ok=True)
    for n, t in texts.items():
        with open(os.path.join(out_dir, n), "w") as fh:
            fh.write(t)
    print("wrote", ", ".join(texts))
